import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    nav_experiences: 'Experiences',
    nav_cabins: 'Cabins',
    nav_boats: 'Transport',
    nav_about: 'About',
    nav_list: 'List Your Experience',
    nav_request_transport: 'Request Transport',
    nav_request_cabin: 'Request Cabin',
    nav_dashboard: 'Dashboard',
    nav_profile: 'My Profile',
    nav_favourites: 'Favourites',
    nav_sign_in: 'Sign in',
    nav_get_started: 'Get started',
    nav_sign_out: 'Sign out',
    nav_create_listing: 'Create listing',
    hero_title: 'Greenland on Local Terms',
    hero_subtitle: 'Authentic Arctic experiences hosted by the people who call it home',
    hero_cta: 'Explore Experiences',
    hero_cta2: 'Browse Cabins',
    search_placeholder: 'Where in Greenland?',
    search_what: 'What experience?',
    search_when: 'When?',
    search_btn: 'Search',
    featured_title: 'Featured Experiences',
    featured_subtitle: 'Hand-picked adventures from local guides across Greenland',
    cabins_title: 'Remote Cabin Stays',
    cabins_subtitle: 'Disconnect in the heart of Arctic nature',
    boats_title: 'Boat Shares',
    boats_subtitle: 'Share a ride with locals heading along the coast',
    how_title: 'How Sila Works',
    how_step1_title: 'Discover',
    how_step1_desc: 'Browse authentic experiences hosted by local Greenlanders',
    how_step2_title: 'Book Directly',
    how_step2_desc: 'Reserve your spot with instant confirmation',
    how_step3_title: 'Experience',
    how_step3_desc: 'Live the Arctic on local terms — guides keep 85% of every booking',
    per_person: 'per person',
    per_night: 'per night',
    per_seat: 'per seat',
    from: 'From',
    hours: 'hours',
    guests: 'guests',
    book_now: 'Book Now',
    view_details: 'View Details',
    reviews: 'reviews',
    available_seats: 'seats available',
    difficulty: 'Difficulty',
    duration: 'Duration',
    languages_spoken: 'Languages',
    included: "What's included",
    season: 'Season',
    all: 'All',
    location: 'Location',
    category: 'Category',
    price: 'Price',
    footer_tagline: 'The Arctic, on local terms.',
    footer_desc: 'Connecting Greenland\'s guides, cabin owners, and boat operators directly with travelers who want the real Arctic.',
    dkk: 'DKK',
    easy: 'Easy',
    moderate: 'Moderate',
    challenging: 'Challenging',
    spring: 'Spring',
    summer: 'Summer',
    autumn: 'Autumn',
    winter: 'Winter',
    boat_tour: 'Boat Tours',
    dog_sledding: 'Dog Sledding',
    kayaking: 'Kayaking',
    northern_lights: 'Northern Lights',
    hiking: 'Hiking',
    fishing: 'Fishing',
    cultural: 'Cultural',
    wildlife: 'Wildlife',
    ice_cap: 'Ice Cap',
    no_results: 'No experiences found',
    loading: 'Loading...',
  },
  da: {
    nav_experiences: 'Oplevelser',
    nav_cabins: 'Hytter',
    nav_boats: 'Transport',
    nav_about: 'Om os',
    nav_list: 'Opret din oplevelse',
    nav_request_transport: 'Anmod om transport',
    nav_request_cabin: 'Anmod om hytte',
    nav_dashboard: 'Dashboard',
    nav_profile: 'Min profil',
    nav_favourites: 'Favoritter',
    nav_sign_in: 'Log ind',
    nav_get_started: 'Kom i gang',
    nav_sign_out: 'Log ud',
    nav_create_listing: 'Opret annonce',
    hero_title: 'Grønland på lokale vilkår',
    hero_subtitle: 'Autentiske arktiske oplevelser fra dem, der kalder det hjem',
    hero_cta: 'Udforsk oplevelser',
    hero_cta2: 'Se hytter',
    search_placeholder: 'Hvor i Grønland?',
    search_what: 'Hvilken oplevelse?',
    search_when: 'Hvornår?',
    search_btn: 'Søg',
    featured_title: 'Udvalgte oplevelser',
    featured_subtitle: 'Håndplukkede eventyr fra lokale guider i Grønland',
    cabins_title: 'Hytter i naturen',
    cabins_subtitle: 'Kobl fra i den arktiske natur',
    boats_title: 'Bådpladser',
    boats_subtitle: 'Del en tur med lokale langs kysten',
    how_title: 'Sådan virker Sila',
    how_step1_title: 'Opdag',
    how_step1_desc: 'Find autentiske oplevelser fra lokale grønlændere',
    how_step2_title: 'Book direkte',
    how_step2_desc: 'Reserver din plads med øjeblikkelig bekræftelse',
    how_step3_title: 'Oplev',
    how_step3_desc: 'Oplev Arktis på lokale vilkår — guider beholder 85% af hver booking',
    per_person: 'pr. person',
    per_night: 'pr. nat',
    per_seat: 'pr. plads',
    from: 'Fra',
    hours: 'timer',
    guests: 'gæster',
    book_now: 'Book nu',
    view_details: 'Se detaljer',
    reviews: 'anmeldelser',
    available_seats: 'pladser tilbage',
    difficulty: 'Sværhedsgrad',
    duration: 'Varighed',
    languages_spoken: 'Sprog',
    included: 'Inkluderet',
    season: 'Sæson',
    all: 'Alle',
    location: 'Sted',
    category: 'Kategori',
    price: 'Pris',
    footer_tagline: 'Arktis, på lokale vilkår.',
    footer_desc: 'Vi forbinder Grønlands guider, hytteejere og bådoperatører direkte med rejsende.',
    dkk: 'DKK',
    easy: 'Let',
    moderate: 'Moderat',
    challenging: 'Udfordrende',
    spring: 'Forår',
    summer: 'Sommer',
    autumn: 'Efterår',
    winter: 'Vinter',
    boat_tour: 'Bådture',
    dog_sledding: 'Hundeslæde',
    kayaking: 'Kajak',
    northern_lights: 'Nordlys',
    hiking: 'Vandring',
    fishing: 'Fiskeri',
    cultural: 'Kultur',
    wildlife: 'Dyreliv',
    ice_cap: 'Indlandsisen',
    no_results: 'Ingen oplevelser fundet',
    loading: 'Indlæser...',
  },
  kl: {
    nav_experiences: 'Suliffinneqarnerit',
    nav_cabins: 'Illut',
    nav_boats: 'Umiarsuit',
    nav_about: 'Pillugu',
    nav_list: 'Suliffinneqarnerit',
    nav_request_transport: 'Umiarsueruk',
    nav_request_cabin: 'Illueruk',
    nav_dashboard: 'Dashboard',
    nav_profile: 'Profili',
    nav_favourites: 'Inerneraat',
    nav_sign_in: 'Loggi-eruk',
    nav_get_started: 'Allariaruk',
    nav_sign_out: 'Loggi-neq',
    nav_create_listing: 'Illu takuuk',
    hero_title: 'Kalaallit Nunaat nunaqarfinni',
    hero_subtitle: 'Arktikkimi pikkorissartut nunaqarfinni',
    hero_cta: 'Suliffinneqarnerit',
    hero_cta2: 'Illut takuuk',
    search_placeholder: 'Kalaallit Nunaanni sumiiffik?',
    search_what: 'Suna?',
    search_when: 'Qaqugu?',
    search_btn: 'Ujarlerit',
    featured_title: 'Suliffinneqarnerit',
    featured_subtitle: 'Kalaallit guidekunngorsimaffinnit',
    cabins_title: 'Illut siniffimmut',
    cabins_subtitle: 'Pinngortitami arktikkimi',
    boats_title: 'Umiarsuit',
    boats_subtitle: 'Nunaqarfinni sinnerlugit',
    how_title: 'Sila qanoq sulisoq',
    how_step1_title: 'Nassaaruk',
    how_step1_desc: 'Kalaallit guidekunngorsimaffinni suliffinneqarnerit',
    how_step2_title: 'Booking-eruk',
    how_step2_desc: 'Inissaq booking-eruk',
    how_step3_title: 'Atuguk',
    how_step3_desc: 'Arktikkimi nunaqarfinni — guidit 85% pigivaat',
    per_person: 'inuttut',
    per_night: 'unnuamut',
    per_seat: 'inissaq',
    from: 'Kiisalu',
    hours: 'nalunaaqutap akunnera',
    guests: 'inuit',
    book_now: 'Booking-eruk',
    view_details: 'Takuuk',
    reviews: 'naliliinerit',
    available_seats: 'inissat',
    dkk: 'DKK',
    all: 'Tamarmik',
    loading: 'Aaqqissuussaaq...',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    // Load from localStorage or default to 'da'
    if (typeof window !== 'undefined') {
      return localStorage.getItem('sila_language') || 'da';
    }
    return 'da';
  });

  const changeLang = (newLang) => {
    setLang(newLang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('sila_language', newLang);
    }
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['da']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}