import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    nav_experiences: 'Experiences',
    nav_cabins: 'Cabins',
    nav_boats: 'Transport',
    nav_about: 'About',
    nav_list: 'List Your Experience',
    nav_request_transport: 'Request Transport',
    nav_request_cabin: 'Request Cabin',
    nav_dashboard: 'Dashboard',
    nav_profile: 'My Profile',
    nav_favourites: 'Favourites',
    nav_sign_in: 'Sign in',
    nav_get_started: 'Get started',
    nav_sign_out: 'Sign out',
    nav_create_listing: 'Create listing',
    hero_title: 'Greenland on Local Terms',
    hero_subtitle: 'Authentic Arctic experiences hosted by the people who call it home',
    hero_cta: 'Explore Experiences',
    hero_cta2: 'Browse Cabins',
    search_placeholder: 'Where in Greenland?',
    search_what: 'What experience?',
    search_when: 'When?',
    search_btn: 'Search',
    featured_title: 'Featured Experiences',
    featured_subtitle: 'Hand-picked adventures from local guides across Greenland',
    cabins_title: 'Remote Cabin Stays',
    cabins_subtitle: 'Disconnect in the heart of Arctic nature',
    boats_title: 'Boat Shares',
    boats_subtitle: 'Share a ride with locals heading along the coast',
    how_title: 'How Sila Works',
    how_step1_title: 'Discover',
    how_step1_desc: 'Browse authentic experiences hosted by local Greenlanders',
    how_step2_title: 'Book Directly',
    how_step2_desc: 'Reserve your spot with instant confirmation',
    how_step3_title: 'Experience',
    how_step3_desc: 'Live the Arctic on local terms — guides keep 85% of every booking',
    per_person: 'per person',
    per_night: 'per night',
    per_seat: 'per seat',
    from: 'From',
    hours: 'hours',
    guests: 'guests',
    book_now: 'Book Now',
    view_details: 'View Details',
    reviews: 'reviews',
    available_seats: 'seats available',
    difficulty: 'Difficulty',
    duration: 'Duration',
    languages_spoken: 'Languages',
    included: "What's included",
    season: 'Season',
    all: 'All',
    location: 'Location',
    category: 'Category',
    price: 'Price',
    footer_tagline: 'The Arctic, on local terms.',
    footer_desc: 'Connecting Greenland\'s guides, cabin owners, and boat operators directly with travelers who want the real Arctic.',
    dkk: 'DKK',
    easy: 'Easy',
    moderate: 'Moderate',
    challenging: 'Challenging',
    spring: 'Spring',
    summer: 'Summer',
    autumn: 'Autumn',
    winter: 'Winter',
    boat_tour: 'Boat Tours',
    dog_sledding: 'Dog Sledding',
    kayaking: 'Kayaking',
    northern_lights: 'Northern Lights',
    hiking: 'Hiking',
    fishing: 'Fishing',
    cultural: 'Cultural',
    wildlife: 'Wildlife',
    ice_cap: 'Ice Cap',
    no_results: 'No experiences found',
    loading: 'Loading...',
    request_transport_title: 'Request Transport',
    request_transport_desc: 'Describe your trip — local sailors and boat owners will respond with a price quote. No fixed price, no hidden fees.',
    select_departure: 'Select departure point',
    select_destination: 'Select destination',
    other_describe: 'Other (describe below)',
    date: 'Date',
    passengers: 'Number of passengers',
    trip_type: 'Trip type',
    outbound: 'Outbound',
    single_way: 'One way',
    return_trip: 'Return',
    round_trip: 'Round trip',
    both_ways: 'Both ways',
    return_date: 'Return date',
    return_passengers: 'Return passengers',
    describe_trip: 'Describe your trip',
    describe_trip_optional: '(optional, but helps the provider)',
    describe_placeholder: 'E.g. we are 2 adults and 1 child. We need to pick up kayak gear. Return trip same day if possible.',
    how_it_works: 'How it works:',
    step1: '1. Send your request — it\'s free and non-binding.',
    step2: '2. Local providers see your request and reply with a price quote.',
    step3: '3. You choose the best offer and confirm.',
    send_request: 'Send request',
    sending: 'Sending...',
    request_sent: 'Request sent!',
    request_sent_desc: 'Local providers will soon answer with a quote.',
    home_return: 'Home return',
    cabins_found: 'cabins found',
    no_cabins_found: 'No cabins found',
    adjust_filters: 'Try adjusting your filters',
    about_cabin: 'About this cabin',
    no_description: 'No description provided.',
    included: 'What\'s included',
    your_host: 'Your host',
    view_profile: 'View profile',
    check_in: 'Check-in',
    check_out: 'Check-out',
    guests: 'Guests',
    message_host_optional: 'Message to host (optional)',
    tell_host: 'Tell the host about your trip...',
    per_night_short: 'DKK / night',
    total: 'Total',
    transport: 'Transport',
    nights_label: 'DKK × nights',
    login_to_book: 'Log in to book',
    secure_payment: 'Secure payment via Stripe',
    back_to_cabins: 'Back to cabins',
    cabin_not_found: 'Cabin not found',
    up_to_guests: 'Up to guests',
    host_provides_transport: 'Host provides transport',
    select_dates_to_book: 'Select dates to book',
    transport_heading: 'Transport heading',
    routes_found: 'routes found',
    no_transport_found: 'No transport found',
    try_another_search: 'Try another search',
    boat_transport: 'Boat transport',
    local_offers: 'Local providers offer available seats on their routes in Greenland',
  },
  da: {
    nav_experiences: 'Oplevelser',
    nav_cabins: 'Hytter',
    nav_boats: 'Transport',
    nav_about: 'Om os',
    nav_list: 'Opret din oplevelse',
    nav_request_transport: 'Anmod om transport',
    nav_request_cabin: 'Anmod om hytte',
    nav_dashboard: 'Dashboard',
    nav_profile: 'Min profil',
    nav_favourites: 'Favoritter',
    nav_sign_in: 'Log ind',
    nav_get_started: 'Kom i gang',
    nav_sign_out: 'Log ud',
    nav_create_listing: 'Opret annonce',
    hero_title: 'Grønland på lokale vilkår',
    hero_subtitle: 'Autentiske arktiske oplevelser fra dem, der kalder det hjem',
    hero_cta: 'Udforsk oplevelser',
    hero_cta2: 'Se hytter',
    search_placeholder: 'Hvor i Grønland?',
    search_what: 'Hvilken oplevelse?',
    search_when: 'Hvornår?',
    search_btn: 'Søg',
    featured_title: 'Udvalgte oplevelser',
    featured_subtitle: 'Håndplukkede eventyr fra lokale guider i Grønland',
    cabins_title: 'Hytter i naturen',
    cabins_subtitle: 'Kobl fra i den arktiske natur',
    boats_title: 'Bådpladser',
    boats_subtitle: 'Del en tur med lokale langs kysten',
    how_title: 'Sådan virker Sila',
    how_step1_title: 'Opdag',
    how_step1_desc: 'Find autentiske oplevelser fra lokale grønlændere',
    how_step2_title: 'Book direkte',
    how_step2_desc: 'Reserver din plads med øjeblikkelig bekræftelse',
    how_step3_title: 'Oplev',
    how_step3_desc: 'Oplev Arktis på lokale vilkår — guider beholder 85% af hver booking',
    per_person: 'pr. person',
    per_night: 'pr. nat',
    per_seat: 'pr. plads',
    from: 'Fra',
    hours: 'timer',
    guests: 'gæster',
    book_now: 'Book nu',
    view_details: 'Se detaljer',
    reviews: 'anmeldelser',
    available_seats: 'pladser tilbage',
    difficulty: 'Sværhedsgrad',
    duration: 'Varighed',
    languages_spoken: 'Sprog',
    included: 'Inkluderet',
    season: 'Sæson',
    all: 'Alle',
    location: 'Sted',
    category: 'Kategori',
    price: 'Pris',
    footer_tagline: 'Arktis, på lokale vilkår.',
    footer_desc: 'Vi forbinder Grønlands guider, hytteejere og bådoperatører direkte med rejsende.',
    dkk: 'DKK',
    easy: 'Let',
    moderate: 'Moderat',
    challenging: 'Udfordrende',
    spring: 'Forår',
    summer: 'Sommer',
    autumn: 'Efterår',
    winter: 'Vinter',
    boat_tour: 'Bådture',
    dog_sledding: 'Hundeslæde',
    kayaking: 'Kajak',
    northern_lights: 'Nordlys',
    hiking: 'Vandring',
    fishing: 'Fiskeri',
    cultural: 'Kultur',
    wildlife: 'Dyreliv',
    ice_cap: 'Indlandsisen',
    no_results: 'Ingen oplevelser fundet',
    loading: 'Indlæser...',
    request_transport_title: 'Anmod om transport',
    request_transport_desc: 'Beskriv din tur — lokale sejlere og bådejere vil svare med et pristilbud. Ingen fast pris, ingen skjulte gebyrer.',
    from: 'Fra',
    to: 'Til',
    select_departure: 'Vælg afgangssted',
    select_destination: 'Vælg destination',
    other_describe: 'Andet (beskriv nedenfor)',
    date: 'Dato',
    passengers: 'Antal passagerer',
    trip_type: 'Rejsetype',
    outbound: 'Afgang',
    single_way: 'Enkelt vej',
    return_trip: 'Retur',
    round_trip: 'Tur/retur',
    both_ways: 'Begge veje',
    return_date: 'Returdato',
    return_passengers: 'Antal passagerer (retur)',
    describe_trip: 'Beskriv din tur',
    describe_trip_optional: '(valgfrit, men hjælper aktøren)',
    describe_placeholder: 'F.eks. vi er 2 voksne og 1 barn. Vi skal hente kajak-udstyr. Returtur samme dag om muligt.',
    how_it_works: 'Sådan fungerer det:',
    step1: '1. Du sender din forespørgsel — det er gratis og uforpligtende.',
    step2: '2. Lokale aktører ser din forespørgsel og svarer med et pristilbud.',
    step3: '3. Du vælger det tilbud, der passer bedst, og bekræfter.',
    send_request: 'Send forespørgsel',
    sending: 'Sender...',
    request_sent: 'Forespørgsel sendt!',
    request_sent_desc: 'Lokale aktører vil snart svare med et tilbud.',
    home_return: 'Hjemrejse',
    cabins_found: 'hytter fundet',
    no_cabins_found: 'Ingen hytter fundet',
    adjust_filters: 'Prøv at justere dine filtre',
    about_cabin: 'Om denne hytte',
    no_description: 'Ingen beskrivelse angivet.',
    check_in: 'Indkvartering',
    check_out: 'Udtjekning',
    message_host_optional: 'Besked til vært (valgfrit)',
    tell_host: 'Fortæl værten om din tur...',
    per_night_short: 'DKK / nat',
    transport: 'Transport',
    nights_label: 'DKK × nætter',
    login_to_book: 'Log ind for at booke',
    secure_payment: 'Sikker betaling via Stripe',
    back_to_cabins: 'Tilbage til hytter',
    cabin_not_found: 'Hytte ikke fundet',
    up_to_guests: 'Op til gæster',
    host_provides_transport: 'Vært tilbyder transport',
    select_dates_to_book: 'Vælg datoer for at booke',
    routes_found: 'ruter fundet',
    no_transport_found: 'Ingen transport fundet',
    try_another_search: 'Prøv en anden søgning',
    local_offers: 'Lokale tilbyder ledige pladser på deres ruter i Grønland',
  },
  kl: {
    nav_experiences: 'Suliffinneqarnerit',
    nav_cabins: 'Illut',
    nav_boats: 'Umiarsuit',
    nav_about: 'Pillugu',
    nav_list: 'Suliffinneqarnerit',
    nav_request_transport: 'Umiarsueruk',
    nav_request_cabin: 'Illueruk',
    nav_dashboard: 'Dashboard',
    nav_profile: 'Profili',
    nav_favourites: 'Inerneraat',
    nav_sign_in: 'Loggi-eruk',
    nav_get_started: 'Allariaruk',
    nav_sign_out: 'Loggi-neq',
    nav_create_listing: 'Illu takuuk',
    hero_title: 'Kalaallit Nunaat nunaqarfinni',
    hero_subtitle: 'Arktikkimi pikkorissartut nunaqarfinni',
    hero_cta: 'Suliffinneqarnerit',
    hero_cta2: 'Illut takuuk',
    search_placeholder: 'Kalaallit Nunaanni sumiiffik?',
    search_what: 'Suna?',
    search_when: 'Qaqugu?',
    search_btn: 'Ujarlerit',
    featured_title: 'Suliffinneqarnerit',
    featured_subtitle: 'Kalaallit guidekunngorsimaffinnit',
    cabins_title: 'Illut siniffimmut',
    cabins_subtitle: 'Pinngortitami arktikkimi',
    boats_title: 'Umiarsuit',
    boats_subtitle: 'Nunaqarfinni sinnerlugit',
    how_title: 'Sila qanoq sulisoq',
    how_step1_title: 'Nassaaruk',
    how_step1_desc: 'Kalaallit guidekunngorsimaffinni suliffinneqarnerit',
    how_step2_title: 'Booking-eruk',
    how_step2_desc: 'Inissaq booking-eruk',
    how_step3_title: 'Atuguk',
    how_step3_desc: 'Arktikkimi nunaqarfinni — guidit 85% pigivaat',
    per_person: 'inuttut',
    per_night: 'unnuamut',
    per_seat: 'inissaq',
    from: 'Kiisalu',
    hours: 'nalunaaqutap akunnera',
    guests: 'inuit',
    book_now: 'Booking-eruk',
    view_details: 'Takuuk',
    reviews: 'naliliinerit',
    available_seats: 'inissat',
    dkk: 'DKK',
    all: 'Tamarmik',
    loading: 'Aaqqissuussaaq...',
    request_transport_title: 'Umiarsueruk',
    request_transport_desc: 'Inissaq suliliaq — nunaqarfinni umiarsuarait svaaq-eruk qanornerisigut.',
    from: 'Kiisalu',
    to: 'Attut',
    select_departure: 'Kiisalu takuuk',
    select_destination: 'Attut takuuk',
    other_describe: 'Arlaaq (suliliaq)',
    date: 'Ullua',
    passengers: 'Inuit',
    trip_type: 'Umiarsueruk allannguutissat',
    outbound: 'Inisseq',
    single_way: 'Inisseq aataatigut',
    return_trip: 'Paluartup',
    round_trip: 'Inisseq-paluartup',
    both_ways: 'Tamaasa',
    return_date: 'Paluartup ullua',
    return_passengers: 'Inuit (paluartup)',
    describe_trip: 'Inissaq suliliaq',
    describe_trip_optional: '(allaortut, tamaasa sujunngitsoorpoq)',
    describe_placeholder: 'Inugujoq: arfellit 2 allannguq 1. Kayak takuutaarpoq. Paluartup ullua sunngavinngitsut.',
    how_it_works: 'Sulisoq:',
    step1: '1. Inissaq takuuk — sulissugujoq arlaarta.',
    step2: '2. Umiarsuarait inissaq takuuk qanornerisigut svaaq-eruk.',
    step3: '3. Qanornerisigut pinngortitsuk tassumik.',
    send_request: 'Inissaq takuuk',
    sending: 'Takussuq...',
    request_sent: 'Inissaq takutut!',
    request_sent_desc: 'Umiarsuarait-quat svaaq-eruk qanornerisigut.',
    home_return: 'Paluartup',
    cabins_found: 'illut',
    no_cabins_found: 'Noanngissagut illut',
    adjust_filters: 'Iluaquttallugu suliaq',
    about_cabin: 'Illu pillugu',
    no_description: 'Suliliaq ninngissuq',
    check_in: 'Illu-eruk',
    check_out: 'Illu-ujooq',
    message_host_optional: 'Illusoq message (allaortut)',
    tell_host: 'Illusoq-mi suliliaq',
    per_night_short: 'DKK / unnuamut',
    transport: 'Umiarsuit',
    nights_label: 'DKK × unnuap',
    login_to_book: 'Booking-eruk loggi',
    secure_payment: 'Sikker payment Stripe',
    back_to_cabins: 'Illut siunnertat',
    cabin_not_found: 'Illu takunngissuq',
    up_to_guests: 'Inuit',
    host_provides_transport: 'Illusoq umiarsuit',
    select_dates_to_book: 'Ulloq takuuk booking',
    routes_found: 'rute',
    no_transport_found: 'Umiarsuit noanngissagut',
    try_another_search: 'Ataata ujarlerit',
    local_offers: 'Nunaqarfinni umiarsuarait inissaat',
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    // Load from localStorage or default to 'da'
    if (typeof window !== 'undefined') {
      return localStorage.getItem('sila_language') || 'da';
    }
    return 'da';
  });

  const changeLang = (newLang) => {
    setLang(newLang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('sila_language', newLang);
    }
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['da']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}