import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    nav_experiences: 'Experiences',
    nav_cabins: 'Cabins',
    nav_boats: 'Transport',
    nav_about: 'About',
    nav_list: 'List Your Experience',
    nav_request_transport: 'Request Transport',
    nav_request_cabin: 'Request Cabin',
    nav_dashboard: 'Dashboard',
    nav_profile: 'My Profile',
    nav_favourites: 'Favourites',
    nav_sign_in: 'Sign in',
    nav_get_started: 'Get started',
    nav_sign_out: 'Sign out',
    nav_create_listing: 'Create listing',
    hero_title: 'Greenland on Local Terms',
    hero_subtitle: 'Authentic Arctic experiences hosted by the people who call it home',
    hero_cta: 'Explore Experiences',
    hero_cta2: 'Browse Cabins',
    search_placeholder: 'Where in Greenland?',
    search_what: 'What experience?',
    search_when: 'When?',
    search_btn: 'Search',
    featured_title: 'Featured Experiences',
    featured_subtitle: 'Hand-picked adventures from local guides across Greenland',
    cabins_title: 'Remote Cabin Stays',
    cabins_subtitle: 'Disconnect in the heart of Arctic nature',
    boats_title: 'Boat Shares',
    boats_subtitle: 'Share a ride with locals heading along the coast',
    how_title: 'How Sila Works',
    how_step1_title: 'Discover',
    how_step1_desc: 'Browse authentic experiences hosted by local Greenlanders',
    how_step2_title: 'Book Directly',
    how_step2_desc: 'Reserve your spot with instant confirmation',
    how_step3_title: 'Experience',
    how_step3_desc: 'Live the Arctic on local terms — guides keep 85% of every booking',
    per_person: 'per person',
    per_night: 'per night',
    per_seat: 'per seat',
    from: 'From',
    hours: 'hours',
    guests: 'guests',
    book_now: 'Book Now',
    view_details: 'View Details',
    reviews: 'reviews',
    available_seats: 'seats available',
    difficulty: 'Difficulty',
    duration: 'Duration',
    languages_spoken: 'Languages',
    included: "What's included",
    season: 'Season',
    all: 'All',
    location: 'Location',
    category: 'Category',
    price: 'Price',
    footer_tagline: 'The Arctic, on local terms.',
    footer_desc: 'Connecting Greenland\'s guides, cabin owners, and boat operators directly with travelers who want the real Arctic.',
    dkk: 'DKK',
    easy: 'Easy',
    moderate: 'Moderate',
    challenging: 'Challenging',
    spring: 'Spring',
    summer: 'Summer',
    autumn: 'Autumn',
    winter: 'Winter',
    boat_tour: 'Boat Tours',
    dog_sledding: 'Dog Sledding',
    kayaking: 'Kayaking',
    northern_lights: 'Northern Lights',
    hiking: 'Hiking',
    fishing: 'Fishing',
    cultural: 'Cultural',
    wildlife: 'Wildlife',
    ice_cap: 'Ice Cap',
    no_results: 'No experiences found',
    loading: 'Loading...',
    request_transport_title: 'Request Transport',
    request_transport_desc: 'Describe your trip — local sailors and boat owners will respond with a price quote. No fixed price, no hidden fees.',
    select_departure: 'Select departure point',
    select_destination: 'Select destination',
    other_describe: 'Other (describe below)',
    date: 'Date',
    passengers: 'Number of passengers',
    trip_type: 'Trip type',
    outbound: 'Outbound',
    single_way: 'One way',
    return_trip: 'Return',
    round_trip: 'Round trip',
    both_ways: 'Both ways',
    return_date: 'Return date',
    return_passengers: 'Return passengers',
    describe_trip: 'Describe your trip',
    describe_trip_optional: '(optional, but helps the provider)',
    describe_placeholder: 'E.g. we are 2 adults and 1 child. We need to pick up kayak gear. Return trip same day if possible.',
    how_it_works: 'How it works:',
    step1: '1. Send your request — it\'s free and non-binding.',
    step2: '2. Local providers see your request and reply with a price quote.',
    step3: '3. You choose the best offer and confirm.',
    send_request: 'Send request',
    sending: 'Sending...',
    request_sent: 'Request sent!',
    request_sent_desc: 'Local providers will soon answer with a quote.',
    home_return: 'Home return',
    cabins_found: 'cabins found',
    no_cabins_found: 'No cabins found',
    adjust_filters: 'Try adjusting your filters',
    about_cabin: 'About this cabin',
    no_description: 'No description provided.',
    included: 'What\'s included',
    your_host: 'Your host',
    view_profile: 'View profile',
    check_in: 'Check-in',
    check_out: 'Check-out',
    guests: 'Guests',
    message_host_optional: 'Message to host (optional)',
    tell_host: 'Tell the host about your trip...',
    per_night_short: 'DKK / night',
    total: 'Total',
    transport: 'Transport',
    nights_label: 'DKK × nights',
    login_to_book: 'Log in to book',
    secure_payment: 'Secure payment via Stripe',
    back_to_cabins: 'Back to cabins',
    cabin_not_found: 'Cabin not found',
    up_to_guests: 'Up to guests',
    host_provides_transport: 'Host provides transport',
    select_dates_to_book: 'Select dates to book',
    transport_heading: 'Transport heading',
    routes_found: 'routes found',
    no_transport_found: 'No transport found',
    try_another_search: 'Try another search',
    boat_transport: 'Boat transport',
    local_offers: 'Local providers offer available seats on their routes in Greenland',
    my_dashboard: 'My overview',
    hello: 'Hi,',
    request_cabin_btn: 'Request cabin',
    request_transport_btn: 'Request transport',
    new_listing: 'New listing',
    admin: 'Admin',
    my_bookings: 'My bookings',
    pending_count: 'pending',
    my_requests: 'My requests',
    see_open_requests: 'View open requests',
    provider_tab: 'Provider',
    history: 'History',
    calendar: 'Calendar',
    my_bookings_guest: 'My bookings (guest)',
    no_bookings: 'No bookings yet',
    explore_cabins: 'Explore cabins',
    booking_requests_provider: 'Booking requests (provider)',
    no_booking_requests: 'No booking requests yet.',
    confirm: 'Confirm',
    decline: 'Decline',
    transport_requests: 'Transport requests',
    cabin_requests: 'Cabin requests',
    my_listings: 'My listings',
    add: 'Add',
    no_listings: 'No listings yet.',
    incoming_cabin_requests: 'Cabin requests (host)',
    incoming_transport_requests: 'Transport requests (skipper)',
    my_trust_score: 'My Trust Score',
    ratings: 'Ratings',
    no_received_ratings: 'No received ratings yet.',
    purchase_history: 'Purchase history',
    no_history: 'No history yet',
    booked: 'Booked',
    login_to_see_profile: 'Log in to see your profile',
    login_btn: 'Log in',
    avg_rating: 'average',
    full_name: 'Full name',
    city_location: 'City / Location',
    phone_optional: 'Phone (optional)',
    languages: 'Languages',
    i_am: 'I am...',
    traveler_desc: 'Traveler – I\'m looking for cabins and transport',
    provider_desc: 'Provider – I offer cabins or transport',
    both_desc: 'Both – I offer and travel myself',
    notifications: 'Notifications',
    email_only: 'Email only',
    sms_only: 'SMS only',
    both_email_sms: 'Both email and SMS',
    no_notifications: 'No notifications',
    about_me: 'About me',
    profile_picture: 'Profile picture (optional)',
    sync_provider_data: 'Sync provider data',
    save_profile: 'Save profile',
    saving: 'Saving...',
    provider_profile: 'Provider profile',
    edit_provider_profile: 'Edit provider profile',
    provider_name: 'Provider name',
    my_cabins: 'My cabins',
    ratings_received: 'Ratings received',
    no_ratings: 'No ratings yet.',
    back_to_transport: 'Back to transport',
    transport_not_found: 'Transport not found',
    provider: 'Provider:',
    date: 'Date',
    departure: 'Departure',
    available_seats: 'Available seats',
    boat: 'Boat',
    book_your_seat: 'Book your seat',
    seats_label: 'Number of seats',
    return_trip: 'Return trip',
    want_other_date: 'Want another date? Send a request',
    no_confirmed_return: 'No confirmed return from this provider yet.',
    no_confirmed_return_any: 'No confirmed return trips on this route yet.',
    no_return_other_providers: 'This provider does not offer a return trip.\n\nOther available transport options to',
    request_return_transport: 'Request return transport',
    send_request_desc: 'Send a request — the provider will reply directly',
    send_request_all_providers: 'Send a request — all local providers will see it and reply directly',
    notice_not_confirmed: 'The return trip is not confirmed yet.',
    request_sent_to_providers: 'Your transport request has been sent to providers. You will hear from them as soon as possible.',
    request_sent_to_all_providers: 'Your request has been sent to all local providers on this route. You will hear from them as soon as possible.',
    request_sent_to_all_desc: 'Your request will be sent to all local providers. You pay nothing now.',
    from: 'From',
    to: 'To',
    desired_date: 'Desired date',
    passengers: 'Passengers',
    message_optional: 'Message (optional)',
    describe_trip: 'Describe your trip...',
    send: 'Send',
    sending_dots: 'Sending...',
    outbound_oneway: 'Outbound (one-way)',
    price_per_seat: 'DKK/seat',
    return_available: 'Return available:',
    selected: 'Selected',
    message_label: 'Message (optional)',
    question_to_provider: 'Any questions for the provider?',
    price_summary: 'Price summary',
    seats_plural: 'seats',
    total_label: 'Total',
    fully_booked: 'Fully booked',
    provider_heading: 'Your provider',
    payment_covers_only: 'This payment covers only the selected part of your trip/booking. Remember to confirm your main booking (cabin/outbound trip) separately.',
    view_profile: 'View profile →',
    edit: 'Edit',
    cancel: 'Cancel',
    error_cabin_not_found: 'Cabin not found',
    transport_tilbydes: 'Transport offered',
    per_night_abbr: '/night',
    no_description_provided: 'No description provided.',
    what_included: 'What\'s included',
    edit_mode: 'Edit',
    saving_profile: 'Saving profile...',
    saved: 'Saved',
    provider_avatar: 'Provider avatar',
    ratings_avg: 'ratings',
    cabins_count: 'cabins',
    seats_left: 'seats left',
    with_cabin: 'With cabin',
    without_cabin: 'Without cabin',
    return_trip_available: 'Return trip available:',
    edit_provider: 'Edit provider',
    requesting: 'Requesting...',
    request_sent_exclaim: 'Request sent!',
    request_desc: 'Your transport request has been sent to providers. You will hear from them soon.',
    homepage_return: 'Home return',
    new_request: 'New request',
    saved: 'saved',
    no_favourites: 'No favorites yet',
    save_on_heart: 'Click the heart on cabins and transport to save them here',
    booking_confirmation: 'Your payment has been processed. You will receive a confirmation email.',
    bookings_ready: 'Your bookings are ready',
    booking_details: 'See all details, communicate with the provider, and keep track of your trip from your dashboard.',
    transport_label: 'Transport',
    cabin: 'Cabin',
    create_listing_desc: 'Share your cabin or boat route with travelers in Greenland',
    cabin_label: 'Cabin',
    cabin_listing_desc: 'List a remote cabin stay',
    transport_listing_desc: 'Offer a boat route',
    cabin_title: 'Cabin title *',
    cabin_title_placeholder: 'e.g. Arctic Wilderness Cabin',
    description: 'Description',
    cabin_description_placeholder: 'Describe your cabin, surroundings, access...',
    price_per_night: 'Price per night (DKK) *',
    max_guests: 'Max guests',
    add_on_services: 'Add-on services',
    add_on_services_desc: 'Offer extra services like bedding, cleaning, firewood etc. for extra payment.',
    cabin_images: 'Cabin photos',
    host_transport: 'I provide transport to the cabin',
    host_transport_desc: 'Guests will see your transport offer directly on your cabin listing',
    pricing_model: 'Pricing model',
    pricing_model_desc: 'The price you enter is for round-trip transport per seat. If a guest only selects one-way transport (e.g. only outbound or only return), the price is automatically calculated as 60% of the amount you enter here.',
    transport_from: 'Transport from (city/harbor)',
    transport_from_placeholder: 'e.g. Nuuk harbor',
    transport_price_per_seat: 'Price per seat (DKK) — round trip',
    publish_cabin: 'Publish cabin',
    publishing: 'Publishing...',
    from_placeholder: 'e.g. Nuuk',
    to_placeholder: 'e.g. Ilulissat',
    departure_date: 'Departure date *',
    departure_time: 'Departure time',
    seats_available: 'Seats available *',
    round_trip_price_per_seat: 'Round-trip price per seat (DKK) *',
    oneway_price_calc: 'One-way price will be auto-calculated as 60% (480 DKK if you enter 800)',
    boat_type: 'Boat type',
    boat_type_placeholder: 'e.g. Speedboat, Fishing boat',
    cabin_onboard: 'Cabin onboard?',
    return_trip_desc: 'Enter when you sail back and how many seats are available. Guests will see this clearly during booking.',
    return_time: 'Return departure time',
    return_seats: 'Return seats',
    return_optional: 'Leave fields empty if you don\'t offer a return trip.',
    notes: 'Notes',
    notes_placeholder: 'Any info for passengers — gear, meeting point, etc.',
    onboard_equipment: 'Equipment onboard',
    equipment_desc: 'Add equipment like life jackets, VHF radio, GPS — separate with commas or press Enter.',
    transport_add_on_desc: 'Offer extra services like fishing rods, meals, binoculars etc. for extra payment.',
    boat_images: 'Boat photos *',
    important: 'Important',
    boat_image_instructions: 'Upload at least one photo of the full boat from outside, so guests can see the boat type and size. Interior or detail-only photos are not accepted.',
    image_required: 'At least one photo is required',
    publish_route: 'Publish route',
    payment_cancelled: 'Payment cancelled',
    payment_cancelled_desc: 'Your payment was not completed and the reservation has been released.',
    try_again: 'Try again',
    to_home: 'To homepage',
    transport_offered: 'Transport offered',
    write_review: 'Write review',
    send_review: 'Send review',
    share_experience_transport: 'Share your experience with this transport...',
    no_reviews_yet: 'No reviews yet.',
    anonymous: 'Anonymous',
    review_sent: 'Review sent',
    review_sent_desc: 'Thank you for your feedback!',
    all_locations: 'All locations',
    newest_first: 'Newest first',
    price_low_high: 'Price: low to high',
    price_high_low: 'Price: high to low',
    advanced: 'Advanced',
    min_price_label: 'Min price (DKK/night)',
    max_price_label: 'Max price (DKK/night)',
    min_guests_label: 'Min. guests',
    check_in_after: 'Check-in after',
    amenities_label: 'Amenities',
    host_offers_transport: 'Host offers transport',
    reset_filters: 'Reset filters',
    search_cabin_placeholder: 'Search by name, location or amenity...',
    all_departures: 'All departures',
    all_destinations: 'All destinations',
    earliest_date: 'Earliest date',
    max_price_seat: 'Max price/seat (DKK)',
    min_seats_label: 'Min. available seats',
    boat_type_label: 'Boat type',
    all_types: 'All types',
    search_route_placeholder: 'Search route (e.g. Nuuk, Ilulissat...)',
    round_trip_label: 'round trip',
    see_and_book: 'View & Book',
    by_provider: 'by',
    map_cabins: 'Cabins',
    map_departures: 'Departures',
    map_destinations: 'Destinations',
    map_per_night: '/night',
    map_see_details: 'See details →',
    map_departure_port: 'Departure port',
    map_destination_label: 'Destination',
    map_routes_available: 'routes available',
    map_avg_roundtrip: 'Avg. round trip',
    map_see_all_routes: 'See all routes →',
    getting_there: 'Getting there',
    host_provided_transport: 'Host-provided transport',
    host_no_transport: 'The host does not offer transport to and from the cabin.',
    offers_transport_from: 'offers transport from',
    to_the_cabin: 'to the cabin',
    the_mainland: 'the mainland',
    i_want: 'I want:',
    round_trip_both: 'Round trip (both ways)',
    outbound_one_way: 'Outbound (one way)',
    return_one_way: 'Return (one way)',
    guest_singular: 'guest',
    guest_plural: 'guests',
    added_to_total: 'added to booking total',
    return_included: 'Return trip included',
    no_transport_listings: 'No transport listings found for this location yet.',
    other_transport_to: 'Other available transport options to',
    date_doesnt_fit: "Date doesn't fit?",
    request_transport_now: 'Request transport now',
    request_transport_heading: 'Request transport',
    request_transport_subtitle: 'Local sailors will reply with a price quote — free and non-binding.',
    request_placeholder: 'E.g. we have a lot of luggage and need to arrive before 2pm...',
    request_success: 'Request sent!',
    request_success_desc: 'Local sailors will reply with a price quote as soon as possible.',
    send_another: 'Send another request',
    pay_amount: 'Pay',
    footer_desc: "Greenland's marketplace for remote cabins and local boat transport.",
    footer_explore: 'Explore',
    footer_browse_cabins: 'Browse Cabins',
    footer_find_transport: 'Find Transport',
    footer_hosts: 'Hosts',
    footer_list_cabin: 'List your cabin',
    footer_offer_transport: 'Offer transport',
    footer_learn: 'Learn',
    footer_trust_score: 'Trust Score',
    footer_verified_safety: 'Verified Safety',
    footer_community_guidelines: 'Community Guidelines',
    footer_legal: 'Legal',
    footer_privacy_policy: 'Privacy Policy',
    footer_terms: 'Terms of Service',
    footer_cookies: 'Cookies & Consent',
    footer_support: 'Support',
    footer_privacy_center: 'Privacy Center',
    footer_contact_support: 'Contact Support',
    cant_find_cabin: 'Can\'t find your dream cabin?',
    request_cabin_cta: 'Tell us what you\'re looking for, and we\'ll match you with the best cabins in Greenland.',
    cant_find_transport: 'Can\'t find the perfect transport route?',
    request_transport_cta: 'Request special transport to any cabin and travel destination in Greenland.',
    show_all_cabins: 'Show all cabins',
    show_all_transport: 'Show all routes',
    incident_title: 'Report an Incident',
    incident_subtitle: 'Your safety matters to us. Report unsafe behavior or policy violations.',
    incident_urgent: 'Emergency?',
    incident_emergency_text: 'If you\'re in immediate danger, please contact local authorities.',
    incident_contact: 'Have questions?',
    incident_form_title: 'Report an Incident',
    incident_form_subtitle: 'Help us maintain safety',
    incident_email: 'Your Email',
    incident_type: 'Incident Type',
    incident_description: 'Description',
    incident_booking: 'Booking ID (optional)',
    incident_involved: 'Involved Parties (emails, comma-separated)',
    incident_submit: 'Submit Report',
    incident_success: 'Incident reported successfully. Our team will review and contact you within 24 hours.',
    incident_error: 'Error submitting report',
    incident_report_submitted: 'Report Submitted',
    incident_submit_another: 'Submit Another',
    incident_select_type: 'Select type',
    incident_type_safety: 'Safety Concern',
    incident_type_harassment: 'Harassment',
    incident_type_fraud: 'Fraud',
    incident_type_damage: 'Property Damage',
    incident_type_other: 'Other',
    support_title: 'Customer Support',
    support_subtitle: 'Get help with bookings, transport, cabins and more.',
    support_faq_title: 'Frequently Asked Questions',
    support_subject_label: 'Subject',
    support_subject_placeholder: 'Choose a question...',
    support_custom_subject_label: 'Describe your subject',
    support_custom_subject_placeholder: 'Write your question or subject here...',
    support_message_label: 'Message',
    support_message_placeholder: 'Describe your problem or question...',
    support_booking_id_label: 'Booking ID',
    support_booking_id_optional: '(optional)',
    support_booking_id_placeholder: 'If your inquiry is about a specific booking',
    support_attachments_label: 'Attach files',
    support_attachments_optional: '(optional)',
    support_uploading: 'Uploading...',
    support_attach_files: 'Choose files to attach',
    support_sending: 'Sending...',
    support_send_btn: 'Send inquiry',
    support_faq_answer_heading: 'Answer to your question',
    support_faq_didnt_help: "Didn't this help? Fill in the form below.",
    support_received_title: 'Inquiry Received',
    support_received_desc: 'Your message has been received. Our support team will respond at support@sila.gl within 24 hours.',
    support_new_inquiry: 'Send a new inquiry',
    support_upload_error: 'Error uploading file',
    support_fill_fields: 'Please fill in all fields',
    support_incident_title: 'Report an Incident',
    support_incident_desc: 'Have you experienced a safety concern, harassment, fraud or another serious incident related to a booking or transport? You can file a confidential report with Sila.',
    support_incident_btn: 'File an incident report',
    faq_q1: 'How do I cancel a booking?',
    faq_q2: 'Can I change my travel dates?',
    faq_q3: 'What payment methods are accepted?',
    faq_q4: 'How do I contact my provider?',
    faq_q5: 'What is your cancellation policy?',
    faq_q6: 'How do I report a safety issue?',
    faq_q7: "I haven't received a confirmation email",
    faq_q8: 'I want to create a listing as a provider',
    faq_other: 'Other — write yourself...',
    faq_a1: 'You can cancel a booking from your dashboard under "My bookings". Find the relevant booking and click "Cancel". Note that our cancellation policy applies — contact us at support@sila.gl if you have questions about refunds.',
    faq_a2: 'Dates cannot be changed directly. You must cancel the existing booking and create a new one. Contact the provider directly via chat, as they may be able to help with a flexible solution.',
    faq_a3: 'We accept all major credit cards (Visa, Mastercard, American Express) via Stripe. Payment is processed securely online — we do not store card details.',
    faq_a4: 'Go to your dashboard and find your booking or request. From there you can open the chat with the provider directly.',
    faq_a5: 'Cancellation terms vary per provider and are visible on each listing before booking. In doubt — contact us at support@sila.gl.',
    faq_a6: 'Use our incident report form under Support → "Report an incident", or write directly to support@sila.gl. Serious situations: contact local authorities.',
    faq_a7: 'Check your spam folder. The email is sent from no-reply@sila.gl. If you still haven\'t received it after 10 minutes, contact us with your booking ID.',
    faq_a8: 'Log in and go to Dashboard → "New listing". You can create cabin stays or boat routes. If you have questions about onboarding, feel free to write to us.',
    ask_provider_title: 'Ask the provider a question',
    ask_provider_placeholder: 'E.g. are dogs allowed? How much luggage fits? Is food served on board?',
    ask_provider_send: 'Send question',
    ask_provider_sending: 'Sending...',
    ask_provider_sent: 'Question sent!',
    ask_provider_sent_desc: 'The provider will reply as soon as possible.',
    ask_provider_login: 'Log in to ask a question',
    welcome_to_sila: 'Welcome to Sila 👋',
    complete_profile_subtitle: 'Fill in your profile — it takes less than a minute',
    get_started: 'Get started',
    onboarding_name_required: 'Please enter your full name.',
    onboarding_city_required: 'Please select your city.',
    onboarding_role_required: 'Please select your role.',
  },
  da: {
    nav_experiences: 'Oplevelser',
    nav_cabins: 'Hytter',
    nav_boats: 'Transport',
    nav_about: 'Om os',
    nav_list: 'Opret din oplevelse',
    nav_request_transport: 'Anmod om transport',
    nav_request_cabin: 'Anmod om hytte',
    nav_dashboard: 'Dashboard',
    nav_profile: 'Min profil',
    nav_favourites: 'Favoritter',
    nav_sign_in: 'Log ind',
    nav_get_started: 'Kom i gang',
    nav_sign_out: 'Log ud',
    nav_create_listing: 'Opret annonce',
    hero_title: 'Grønland på lokale vilkår',
    hero_subtitle: 'Autentiske arktiske oplevelser fra dem, der kalder det hjem',
    hero_cta: 'Udforsk oplevelser',
    hero_cta2: 'Se hytter',
    search_placeholder: 'Hvor i Grønland?',
    search_what: 'Hvilken oplevelse?',
    search_when: 'Hvornår?',
    search_btn: 'Søg',
    featured_title: 'Udvalgte oplevelser',
    featured_subtitle: 'Håndplukkede eventyr fra lokale guider i Grønland',
    cabins_title: 'Hytter i naturen',
    cabins_subtitle: 'Kobl fra i den arktiske natur',
    boats_title: 'Bådpladser',
    boats_subtitle: 'Del en tur med lokale langs kysten',
    how_title: 'Sådan virker Sila',
    how_step1_title: 'Opdag',
    how_step1_desc: 'Find autentiske oplevelser fra lokale grønlændere',
    how_step2_title: 'Book direkte',
    how_step2_desc: 'Reserver din plads med øjeblikkelig bekræftelse',
    how_step3_title: 'Oplev',
    how_step3_desc: 'Oplev Arktis på lokale vilkår — guider beholder 85% af hver booking',
    per_person: 'pr. person',
    per_night: 'pr. nat',
    per_seat: 'pr. plads',
    from: 'Fra',
    hours: 'timer',
    guests: 'gæster',
    book_now: 'Book nu',
    view_details: 'Se detaljer',
    reviews: 'anmeldelser',
    available_seats: 'pladser tilbage',
    difficulty: 'Sværhedsgrad',
    duration: 'Varighed',
    languages_spoken: 'Sprog',
    included: 'Inkluderet',
    season: 'Sæson',
    all: 'Alle',
    location: 'Sted',
    category: 'Kategori',
    price: 'Pris',
    footer_tagline: 'Arktis, på lokale vilkår.',
    footer_desc: 'Vi forbinder Grønlands guider, hytteejere og bådoperatører direkte med rejsende.',
    dkk: 'DKK',
    easy: 'Let',
    moderate: 'Moderat',
    challenging: 'Udfordrende',
    spring: 'Forår',
    summer: 'Sommer',
    autumn: 'Efterår',
    winter: 'Vinter',
    boat_tour: 'Bådture',
    dog_sledding: 'Hundeslæde',
    kayaking: 'Kajak',
    northern_lights: 'Nordlys',
    hiking: 'Vandring',
    fishing: 'Fiskeri',
    cultural: 'Kultur',
    wildlife: 'Dyreliv',
    ice_cap: 'Indlandsisen',
    no_results: 'Ingen oplevelser fundet',
    loading: 'Indlæser...',
    request_transport_title: 'Anmod om transport',
    request_transport_desc: 'Beskriv din tur — lokale sejlere og bådejere vil svare med et pristilbud. Ingen fast pris, ingen skjulte gebyrer.',
    from: 'Fra',
    to: 'Til',
    select_departure: 'Vælg afgangssted',
    select_destination: 'Vælg destination',
    other_describe: 'Andet (beskriv nedenfor)',
    date: 'Dato',
    passengers: 'Antal passagerer',
    trip_type: 'Rejsetype',
    outbound: 'Afgang',
    single_way: 'Enkelt vej',
    return_trip: 'Retur',
    round_trip: 'Tur/retur',
    both_ways: 'Begge veje',
    return_date: 'Returdato',
    return_passengers: 'Antal passagerer (retur)',
    describe_trip: 'Beskriv din tur',
    describe_trip_optional: '(valgfrit, men hjælper aktøren)',
    describe_placeholder: 'F.eks. vi er 2 voksne og 1 barn. Vi skal hente kajak-udstyr. Returtur samme dag om muligt.',
    how_it_works: 'Sådan fungerer det:',
    step1: '1. Du sender din forespørgsel — det er gratis og uforpligtende.',
    step2: '2. Lokale aktører ser din forespørgsel og svarer med et pristilbud.',
    step3: '3. Du vælger det tilbud, der passer bedst, og bekræfter.',
    send_request: 'Send forespørgsel',
    sending: 'Sender...',
    request_sent: 'Forespørgsel sendt!',
    request_sent_desc: 'Lokale aktører vil snart svare med et tilbud.',
    home_return: 'Hjemrejse',
    cabins_found: 'hytter fundet',
    no_cabins_found: 'Ingen hytter fundet',
    adjust_filters: 'Prøv at justere dine filtre',
    about_cabin: 'Om denne hytte',
    no_description: 'Ingen beskrivelse angivet.',
    check_in: 'Indkvartering',
    check_out: 'Udtjekning',
    message_host_optional: 'Besked til vært (valgfrit)',
    tell_host: 'Fortæl værten om din tur...',
    per_night_short: 'DKK / nat',
    transport: 'Transport',
    nights_label: 'DKK × nætter',
    login_to_book: 'Log ind for at booke',
    secure_payment: 'Sikker betaling via Stripe',
    back_to_cabins: 'Tilbage til hytter',
    cabin_not_found: 'Hytte ikke fundet',
    up_to_guests: 'Op til gæster',
    host_provides_transport: 'Vært tilbyder transport',
    select_dates_to_book: 'Vælg datoer for at booke',
    routes_found: 'ruter fundet',
    no_transport_found: 'Ingen transport fundet',
    try_another_search: 'Prøv en anden søgning',
    local_offers: 'Lokale tilbyder ledige pladser på deres ruter i Grønland',
    my_dashboard: 'Mit overblik',
    hello: 'Hej,',
    request_cabin_btn: 'Anmod om hytte',
    request_transport_btn: 'Anmod om transport',
    new_listing: 'Nyt opslag',
    admin: 'Admin',
    my_bookings: 'Mine bookinger',
    pending_count: 'afventer',
    my_requests: 'Mine forespørgsler',
    see_open_requests: 'Se åbne ønsker',
    provider_tab: 'Udbyder',
    history: 'Historik',
    calendar: 'Kalender',
    my_bookings_guest: 'Mine bookinger (gæst)',
    no_bookings: 'Ingen bookinger endnu',
    explore_cabins: 'Udforsk hytter',
    booking_requests_provider: 'Bookingforespørgsler (udbyder)',
    no_booking_requests: 'Ingen bookingforespørgsler endnu.',
    confirm: 'Bekræft',
    decline: 'Afvis',
    transport_requests: 'Transportforespørgsler',
    cabin_requests: 'Hytteforespørgsler',
    my_listings: 'Mine opslag',
    add: 'Tilføj',
    no_listings: 'Ingen opslag endnu.',
    incoming_cabin_requests: 'Hytteforespørgsler (vært)',
    incoming_transport_requests: 'Transportforespørgsler (skipper)',
    my_trust_score: 'Min Trust Score',
    ratings: 'Bedømmelser',
    no_received_ratings: 'Ingen modtagne bedømmelser endnu.',
    purchase_history: 'Købshistorik',
    no_history: 'Ingen historik endnu',
    booked: 'Booket',
    login_to_see_profile: 'Log ind for at se din profil',
    login_btn: 'Log ind',
    avg_rating: 'gennemsnit',
    full_name: 'Fulde navn',
    city_location: 'By / Sted',
    phone_optional: 'Telefon (valgfri)',
    languages: 'Sprog',
    i_am: 'Jeg er...',
    traveler_desc: 'Rejsende – jeg leder efter hytter og transport',
    provider_desc: 'Udbyder – jeg tilbyder hytter eller transport',
    both_desc: 'Begge – jeg udbyder og rejser selv',
    notifications: 'Notifikationer',
    email_only: 'Kun e-mail',
    sms_only: 'Kun SMS',
    both_email_sms: 'Både e-mail og SMS',
    no_notifications: 'Ingen notifikationer',
    about_me: 'Om mig',
    profile_picture: 'Profilbillede (valgfri)',
    sync_provider_data: 'Synkroniser udbyder-data',
    save_profile: 'Gem profil',
    saving: 'Gemmer...',
    provider_profile: 'Udbyder-profil',
    edit_provider_profile: 'Rediger udbyder-profil',
    provider_name: 'Udbyder navn',
    my_cabins: 'Mine hytter',
    ratings_received: 'Bedømmelser',
    no_ratings: 'Ingen bedømmelser endnu.',
    back_to_transport: 'Tilbage til transport',
    transport_not_found: 'Transport ikke fundet',
    provider: 'Udbyder:',
    date: 'Dato',
    departure: 'Afgang',
    available_seats: 'Ledige pladser',
    boat: 'Båd',
    book_your_seat: 'Book din plads',
    seats_label: 'Antal pladser',
    return_trip: 'Hjemrejse',
    want_other_date: 'Ønsker du en anden dato? Send en anmodning',
    no_confirmed_return: 'Ingen bekræftet hjemrejse fra denne udbyder endnu.',
    no_confirmed_return_any: 'Ingen bekræftede hjemrejser på denne rute endnu.',
    no_return_other_providers: 'Denne udbyder tilbyder ikke hjemrejse.\n\nAndre tilgængelige transportmuligheder til',
    request_return_transport: 'Anmod om returtransport',
    send_request_desc: 'Send en anmodning — udbyderen svarer dig direkte',
    send_request_all_providers: 'Send en anmodning — alle lokale udbydere ser den og svarer dig direkte',
    notice_not_confirmed: 'Hjemrejsen er ikke bekræftet endnu.',
    request_sent_to_providers: 'Din transportanmodning er sendt til udbyderne. Du hører fra dem hurtigst muligt.',
    request_sent_to_all_providers: 'Din anmodning er sendt til alle lokale udbydere på denne rute. Du hører fra dem hurtigst muligt.',
    request_sent_to_all_desc: 'Din anmodning sendes til alle lokale udbydere. Du betaler intet nu.',
    from: 'Fra',
    to: 'Til',
    desired_date: 'Ønsket dato',
    passengers: 'Passagerer',
    message_optional: 'Besked (valgfri)',
    describe_trip: 'Beskriv din rejse...',
    send: 'Send',
    sending_dots: 'Sender...',
    outbound_oneway: 'Udrejse (enkeltbillet)',
    price_per_seat: 'DKK/plads',
    return_available: 'Hjemrejse tilgængelig:',
    selected: 'Valgt',
    message_label: 'Besked (valgfri)',
    question_to_provider: 'Spørgsmål til udbyderen?',
    price_summary: 'Prissammenfattelse',
    seats_plural: 'pladser',
    total_label: 'I alt',
    fully_booked: 'Fuldt booket',
    provider_heading: 'Din udbyder',
    payment_covers_only: 'Denne betaling dækker kun den valgte del af din rejse/booking. Husk at bekræfte din hovedbooking (hytte/udrejse) separat.',
    view_profile: 'Se profil →',
    edit: 'Rediger',
    cancel: 'Annuller',
    error_cabin_not_found: 'Hytte ikke fundet',
    transport_tilbydes: 'Transport tilbydes',
    per_night_abbr: '/nat',
    no_description_provided: 'Ingen beskrivelse angivet.',
    what_included: 'Hvad der er inkluderet',
    edit_mode: 'Rediger',
    saving_profile: 'Gemmer profil...',
    saved: 'Gemt',
    provider_avatar: 'Udbyder avatar',
    ratings_avg: 'bedømmelser',
    cabins_count: 'hytter',
    seats_left: 'pladser tilbage',
    with_cabin: 'Med kabine',
    without_cabin: 'Uden kabine',
    return_trip_available: 'Hjemrejse tilgængelig:',
    edit_provider: 'Rediger udbyder',
    requesting: 'Anmoder...',
    request_sent_exclaim: 'Anmodning sendt!',
    request_desc: 'Din transportanmodning er sendt til udbyderne. Du hører fra dem snart.',
    homepage_return: 'Hjemrejse',
    new_request: 'Ny forespørgsel',
    saved: 'gemte',
    no_favourites: 'Ingen favoritter endnu',
    save_on_heart: 'Tryk på hjertet på hytter og transport for at gemme dem her',
    booking_confirmation: 'Din betaling er gennemført. Du vil modtage en bekræftelse på e-mail.',
    bookings_ready: 'Dine bookinger er klar',
    booking_details: 'Se alle detaljer, kommunikér med udbyderen og hold styr på din rejse fra dit dashboard.',
    transport_label: 'Transport',
    cabin: 'Hytte',
    create_listing_desc: 'Del din hytte eller bådrute med rejsende i Grønland',
    cabin_label: 'Hytte',
    cabin_listing_desc: 'Opret et hytteophold',
    transport_listing_desc: 'Tilbyd en bådrute',
    cabin_title: 'Hytte-titel *',
    cabin_title_placeholder: 'f.eks. Arktisk naturhytte',
    description: 'Beskrivelse',
    cabin_description_placeholder: 'Beskriv din hytte, omgivelser, adgang...',
    price_per_night: 'Pris pr. nat (DKK) *',
    max_guests: 'Maks. gæster',
    add_on_services: 'Tilvalgsydelser',
    add_on_services_desc: 'Tilbyd ekstra services som sengelinned, rengøring, brænde mv. mod ekstra betaling.',
    cabin_images: 'Billeder af hytten',
    host_transport: 'Jeg yder transport til hytten',
    host_transport_desc: 'Gæster vil se dit transporttilbud direkte på dit hytteopslag',
    pricing_model: 'Prismodel',
    pricing_model_desc: 'Den pris du indtaster er for tur/retur transport pr. sæde. Hvis en gæst kun vælger énvejs transport (f.eks. kun hen eller kun tilbage), beregnes prisen automatisk til 60% af det beløb, du angiver her.',
    transport_from: 'Transport fra (by/havn)',
    transport_from_placeholder: 'f.eks. Nuuk havn',
    transport_price_per_seat: 'Pris pr. plads (DKK) — tur/retur',
    publish_cabin: 'Publicer hytte',
    publishing: 'Publicerer...',
    from_placeholder: 'f.eks. Nuuk',
    to_placeholder: 'f.eks. Ilulissat',
    departure_date: 'Afrejsedato *',
    departure_time: 'Afgangstid',
    seats_available: 'Ledige pladser *',
    round_trip_price_per_seat: 'Tur/retur pris pr. plads (DKK) *',
    oneway_price_calc: 'Enkeltbilletpris beregnes automatisk som 60% (480 DKK hvis du indtaster 800)',
    boat_type: 'Bådtype',
    boat_type_placeholder: 'f.eks. Speedbåd, Fiskerbåd',
    cabin_onboard: 'Kabine om bord?',
    return_trip_desc: 'Angiv hvornår I sejler tilbage, og hvor mange pladser der er tilgængelige. Gæster vil se dette tydeligt under booking.',
    return_time: 'Afgang retur (tid)',
    return_seats: 'Pladser retur',
    return_optional: 'Lad felterne stå tomme, hvis du ikke tilbyder hjemrejse.',
    notes: 'Noter',
    notes_placeholder: 'Info til passagerer — udstyr, mødested, mv.',
    onboard_equipment: 'Udstyr om bord',
    equipment_desc: 'Tilføj udstyr som redningsveste, VHF-radio, GPS – adskil med komma eller tryk Enter.',
    transport_add_on_desc: 'Tilbyd ekstra services som fiskestænger, måltider, kikkertudlejning mv. mod ekstra betaling.',
    boat_images: 'Billeder af båden *',
    important: 'Vigtigt',
    boat_image_instructions: 'Upload mindst ét billede af hele båden udefra, så gæster kan se bådtype og størrelse. Billeder af interiør eller detaljer alene accepteres ikke.',
    image_required: 'Mindst ét billede er påkrævet',
    publish_route: 'Publicer rute',
    payment_cancelled: 'Betaling annulleret',
    payment_cancelled_desc: 'Din betaling blev ikke gennemført, og reservationen er frigivet.',
    try_again: 'Prøv igen',
    to_home: 'Til forsiden',
    transport_offered: 'Transport tilbydes',
    write_review: 'Skriv anmeldelse',
    send_review: 'Send anmeldelse',
    share_experience_transport: 'Del din oplevelse med transporten...',
    no_reviews_yet: 'Ingen anmeldelser endnu.',
    anonymous: 'Anonym',
    review_sent: 'Anmeldelse sendt',
    review_sent_desc: 'Tak for din feedback!',
    all_locations: 'Alle steder',
    newest_first: 'Nyeste først',
    price_low_high: 'Pris: lav til høj',
    price_high_low: 'Pris: høj til lav',
    advanced: 'Avanceret',
    min_price_label: 'Min pris (DKK/nat)',
    max_price_label: 'Max pris (DKK/nat)',
    min_guests_label: 'Min. gæster',
    check_in_after: 'Indflytning efter',
    amenities_label: 'Faciliteter',
    host_offers_transport: 'Værten tilbyder transport',
    reset_filters: 'Nulstil filtre',
    search_cabin_placeholder: 'Søg på navn, sted eller facilitet...',
    all_departures: 'Alle afgange',
    all_destinations: 'Alle destinationer',
    earliest_date: 'Tidligste dato',
    max_price_seat: 'Max pris/sæde (DKK)',
    min_seats_label: 'Min. ledige pladser',
    boat_type_label: 'Bådtype',
    all_types: 'Alle typer',
    search_route_placeholder: 'Søg rute (f.eks. Nuuk, Ilulissat...)',
    round_trip_label: 'tur/retur',
    see_and_book: 'Se & Book',
    by_provider: 'af',
    map_cabins: 'Hytter',
    map_departures: 'Afgangshavne',
    map_destinations: 'Destinationer',
    map_per_night: '/nat',
    map_see_details: 'Se detaljer →',
    map_departure_port: 'Afgangshavn',
    map_destination_label: 'Destination',
    map_routes_available: 'ruter tilgængelig',
    map_avg_roundtrip: 'Gns. tur/retur',
    map_see_all_routes: 'Se alle ruter →',
    getting_there: 'Kom dertil',
    host_provided_transport: 'Værtens transport',
    host_no_transport: 'Værten tilbyder ikke transport til og fra hytten.',
    offers_transport_from: 'tilbyder transport fra',
    to_the_cabin: 'til hytten',
    the_mainland: 'fastlandet',
    i_want: 'Jeg ønsker:',
    round_trip_both: 'Tur-retur (begge veje)',
    outbound_one_way: 'Udrejse (enkeltbillet)',
    return_one_way: 'Hjemrejse (enkeltbillet)',
    guest_singular: 'gæst',
    guest_plural: 'gæster',
    added_to_total: 'lægges til bookingprisen',
    return_included: 'Hjemrejse inkluderet',
    no_transport_listings: 'Ingen transportopslag fundet til denne destination endnu.',
    other_transport_to: 'Andre tilgængelige transportmuligheder til',
    date_doesnt_fit: 'Passer datoen ikke?',
    request_transport_now: 'Anmod om transport nu',
    request_transport_heading: 'Anmod om transport',
    request_transport_subtitle: 'Lokale sejlere svarer med et pristilbud — gratis og uforpligtende.',
    request_placeholder: 'F.eks. vi har meget bagage, og ønsker at ankomme inden kl. 14...',
    request_success: 'Forespørgsel sendt!',
    request_success_desc: 'Lokale sejlere vil svare med et pristilbud hurtigst muligt.',
    send_another: 'Send en ny forespørgsel',
    pay_amount: 'Betal',
    footer_desc: 'Vi forbinder Grønlands guider, hytteejere og bådoperatører direkte med rejsende.',
    footer_explore: 'Udforsk',
    footer_browse_cabins: 'Se hytter',
    footer_find_transport: 'Find transport',
    footer_hosts: 'Værter',
    footer_list_cabin: 'Opret din hytte',
    footer_offer_transport: 'Tilbyd transport',
    footer_learn: 'Lær mere',
    footer_trust_score: 'Tillids-score',
    footer_verified_safety: 'Certificeret sikkerhed',
    footer_community_guidelines: 'Fællesskabsretningslinjer',
    footer_legal: 'Juridisk',
    footer_privacy_policy: 'Privatlivspolitik',
    footer_terms: 'Vilkår og betingelser',
    footer_cookies: 'Cookies & Samtykke',
    footer_support: 'Support',
    footer_privacy_center: 'Privatlivscenter',
    footer_contact_support: 'Kontakt support',
    cant_find_cabin: 'Kan du ikke finde din drømmehytte?',
    request_cabin_cta: 'Fortæl os hvad du leder efter, og vi matcher dig med de bedste hytter i Grønland.',
    cant_find_transport: 'Kan du ikke finde den perfekte transportrute?',
    request_transport_cta: 'Anmod om særlig transport til alle hytter og rejsedestinationer i Grønland.',
    show_all_cabins: 'Vis alle hytter',
    show_all_transport: 'Vis alle ruter',
    incident_title: 'Rapportér en hændelse',
    incident_subtitle: 'Din sikkerhed betyder meget for os. Rapportér usikker adfærd eller politikovertrædelser.',
    incident_urgent: 'Nødsituation?',
    incident_emergency_text: 'Hvis du er i umiddelbar fare, kontakt venligst de lokale myndigheder.',
    incident_contact: 'Har du spørgsmål?',
    incident_form_title: 'Rapportér en hændelse',
    incident_form_subtitle: 'Hjælp os med at opretholde sikkerhed',
    incident_email: 'Din e-mail',
    incident_type: 'Hændelses type',
    incident_description: 'Beskrivelse',
    incident_booking: 'Booking ID (valgfrit)',
    incident_involved: 'Involverede parter (e-mails, komma-adskilt)',
    incident_submit: 'Indsend rapport',
    incident_success: 'Hændelse rapporteret med succes. Vores team vil gennemgå og kontakte dig inden 24 timer.',
    incident_error: 'Fejl ved indsendelse af rapport',
    incident_report_submitted: 'Rapport indsendt',
    incident_submit_another: 'Indsend en anden',
    incident_select_type: 'Vælg type',
    incident_type_safety: 'Sikkerhedsproblemer',
    incident_type_harassment: 'Chikane',
    incident_type_fraud: 'Bedrageri',
    incident_type_damage: 'Ejendomsskade',
    incident_type_other: 'Andet',
    support_title: 'Kundesupport',
    support_subtitle: 'Få hjælp til bookinger, transport, hytter og mere.',
    support_faq_title: 'Ofte stillede spørgsmål',
    support_subject_label: 'Emne',
    support_subject_placeholder: 'Vælg et spørgsmål...',
    support_custom_subject_label: 'Beskriv dit emne',
    support_custom_subject_placeholder: 'Skriv dit spørgsmål eller emne her...',
    support_message_label: 'Besked',
    support_message_placeholder: 'Beskriv dit problem eller spørgsmål...',
    support_booking_id_label: 'Booking ID',
    support_booking_id_optional: '(valgfrit)',
    support_booking_id_placeholder: 'Hvis din henvendelse handler om en specifik booking',
    support_attachments_label: 'Vedhæft filer',
    support_attachments_optional: '(valgfrit)',
    support_uploading: 'Uploader...',
    support_attach_files: 'Vælg filer at vedhæfte',
    support_sending: 'Sender...',
    support_send_btn: 'Send henvendelse',
    support_faq_answer_heading: 'Svar på dit spørgsmål',
    support_faq_didnt_help: 'Hjalp dette ikke? Udfyld formularen nedenfor.',
    support_received_title: 'Henvendelse modtaget',
    support_received_desc: 'Din besked er modtaget. Vores supportteam svarer på support@sila.gl inden 24 timer.',
    support_new_inquiry: 'Send en ny henvendelse',
    support_upload_error: 'Fejl ved upload af fil',
    support_fill_fields: 'Udfyld venligst alle felter',
    support_incident_title: 'Rapportér en hændelse',
    support_incident_desc: 'Har du oplevet en sikkerhedsmæssig bekymring, chikane, svindel eller en anden alvorlig hændelse i forbindelse med en booking eller transport? Du kan indgive en fortrolig rapport til Sila.',
    support_incident_btn: 'Indgiv en hændelsesrapport',
    faq_q1: 'Hvordan annullerer jeg en booking?',
    faq_q2: 'Kan jeg ændre mine rejsedatoer?',
    faq_q3: 'Hvilke betalingsmetoder accepteres?',
    faq_q4: 'Hvordan kontakter jeg min udbyder?',
    faq_q5: 'Hvad er jeres afbestillingspolitik?',
    faq_q6: 'Hvordan rapporterer jeg et sikkerhedsproblem?',
    faq_q7: 'Jeg har ikke modtaget en bekræftelsesmail',
    faq_q8: 'Jeg vil oprette et opslag som udbyder',
    faq_other: 'Andet — skriv selv...',
    faq_a1: 'Du kan annullere en booking fra dit dashboard under "Mine bookinger". Find den relevante booking og klik på "Annuller". Bemærk at vores afbestillingspolitik gælder — kontakt os på support@sila.gl hvis du har spørgsmål til refundering.',
    faq_a2: 'Datoer kan ikke ændres direkte. Du skal annullere den eksisterende booking og oprette en ny. Kontakt udbyderen direkte via chat, da de muligvis kan hjælpe med en fleksibel løsning.',
    faq_a3: 'Vi accepterer alle større kreditkort (Visa, Mastercard, American Express) via Stripe. Betaling sker sikkert online — vi gemmer ikke kortoplysninger.',
    faq_a4: 'Gå til dit dashboard og find din booking eller forespørgsel. Herfra kan du åbne chatten med udbyderen direkte.',
    faq_a5: 'Afbestillingsbetingelserne varierer pr. udbyder og er synlige på hvert opslag inden booking. Ved tvivl — kontakt os på support@sila.gl.',
    faq_a6: 'Brug vores hændelsesrapport-formular under Support → "Rapportér en hændelse", eller skriv direkte til support@sila.gl. Alvorlige situationer: kontakt lokale myndigheder.',
    faq_a7: 'Tjek din spam-mappe. Mailen sendes fra no-reply@sila.gl. Har du stadig ikke modtaget den efter 10 minutter, så kontakt os med dit booking-ID.',
    faq_a8: 'Log ind og gå til Dashboard → "Nyt opslag". Du kan oprette hytteophold eller bådruter. Har du spørgsmål til onboarding, er du velkommen til at skrive til os.',
    ask_provider_title: 'Stil et spørgsmål til udbyderen',
    ask_provider_placeholder: 'F.eks. må man tage hund med? Hvor meget bagage er der plads til? Er der mad om bord?',
    ask_provider_send: 'Send spørgsmål',
    ask_provider_sending: 'Sender...',
    ask_provider_sent: 'Spørgsmål sendt!',
    ask_provider_sent_desc: 'Udbyderen svarer hurtigst muligt.',
    ask_provider_login: 'Log ind for at stille et spørgsmål',
    welcome_to_sila: 'Velkommen til Sila 👋',
    complete_profile_subtitle: 'Udfyld din profil — det tager under et minut',
    get_started: 'Kom i gang',
    onboarding_name_required: 'Angiv venligst dit fulde navn.',
    onboarding_city_required: 'Vælg venligst din by.',
    onboarding_role_required: 'Vælg venligst din rolle.',
  },
  kl: {
    nav_experiences: 'Suliffinneqarnerit',
    nav_cabins: 'Illut',
    nav_boats: 'Umiarsuit',
    nav_about: 'Pillugu',
    nav_list: 'Suliffinneqarnerit',
    nav_request_transport: 'Umiarsueruk',
    nav_request_cabin: 'Illueruk',
    nav_dashboard: 'Dashboard',
    nav_profile: 'Profili',
    nav_favourites: 'Inerneraat',
    nav_sign_in: 'Loggi-eruk',
    nav_get_started: 'Allariaruk',
    nav_sign_out: 'Loggi-neq',
    nav_create_listing: 'Illu takuuk',
    hero_title: 'Kalaallit Nunaat nunaqarfinni',
    hero_subtitle: 'Arktikkimi pikkorissartut nunaqarfinni',
    hero_cta: 'Suliffinneqarnerit',
    hero_cta2: 'Illut takuuk',
    search_placeholder: 'Kalaallit Nunaanni sumiiffik?',
    search_what: 'Suna?',
    search_when: 'Qaqugu?',
    search_btn: 'Ujarlerit',
    featured_title: 'Suliffinneqarnerit',
    featured_subtitle: 'Kalaallit guidekunngorsimaffinnit',
    cabins_title: 'Illut siniffimmut',
    cabins_subtitle: 'Pinngortitami arktikkimi',
    boats_title: 'Umiarsuit',
    boats_subtitle: 'Nunaqarfinni sinnerlugit',
    how_title: 'Sila qanoq sulisoq',
    how_step1_title: 'Nassaaruk',
    how_step1_desc: 'Kalaallit guidekunngorsimaffinni suliffinneqarnerit',
    how_step2_title: 'Booking-eruk',
    how_step2_desc: 'Inissaq booking-eruk',
    how_step3_title: 'Atuguk',
    how_step3_desc: 'Arktikkimi nunaqarfinni — guidit 85% pigivaat',
    per_person: 'inuttut',
    per_night: 'unnuamut',
    per_seat: 'inissaq',
    from: 'Kiisalu',
    hours: 'nalunaaqutap akunnera',
    guests: 'inuit',
    book_now: 'Booking-eruk',
    view_details: 'Takuuk',
    reviews: 'naliliinerit',
    available_seats: 'inissat',
    dkk: 'DKK',
    all: 'Tamarmik',
    loading: 'Aaqqissuussaaq...',
    request_transport_title: 'Umiarsueruk',
    request_transport_desc: 'Inissaq suliliaq — nunaqarfinni umiarsuarait svaaq-eruk qanornerisigut.',
    from: 'Kiisalu',
    to: 'Attut',
    select_departure: 'Kiisalu takuuk',
    select_destination: 'Attut takuuk',
    other_describe: 'Arlaaq (suliliaq)',
    date: 'Ullua',
    passengers: 'Inuit',
    trip_type: 'Umiarsueruk allannguutissat',
    outbound: 'Inisseq',
    single_way: 'Inisseq aataatigut',
    return_trip: 'Paluartup',
    round_trip: 'Inisseq-paluartup',
    both_ways: 'Tamaasa',
    return_date: 'Paluartup ullua',
    return_passengers: 'Inuit (paluartup)',
    describe_trip: 'Inissaq suliliaq',
    describe_trip_optional: '(allaortut, tamaasa sujunngitsoorpoq)',
    describe_placeholder: 'Inugujoq: arfellit 2 allannguq 1. Kayak takuutaarpoq. Paluartup ullua sunngavinngitsut.',
    how_it_works: 'Sulisoq:',
    step1: '1. Inissaq takuuk — sulissugujoq arlaarta.',
    step2: '2. Umiarsuarait inissaq takuuk qanornerisigut svaaq-eruk.',
    step3: '3. Qanornerisigut pinngortitsuk tassumik.',
    send_request: 'Inissaq takuuk',
    sending: 'Takussuq...',
    request_sent: 'Inissaq takutut!',
    request_sent_desc: 'Umiarsuarait-quat svaaq-eruk qanornerisigut.',
    provider: 'Suliartortitsisoq:',
    provider_heading: 'Suliartortitsisoq ineq',
    payment_covers_only: 'Akiliut una angalanerit/booking-erit ilaanut kisimi atuuppoq. Eqqaamallugu illua/aningaaserivik immikkoortullu oqartussaaqqusinngisaannarnerani.',
    home_return: 'Paluartup',
    cabins_found: 'illut',
    no_cabins_found: 'Noanngissagut illut',
    adjust_filters: 'Iluaquttallugu suliaq',
    about_cabin: 'Illu pillugu',
    no_description: 'Suliliaq ninngissuq',
    check_in: 'Illu-eruk',
    check_out: 'Illu-ujooq',
    message_host_optional: 'Illusoq message (allaortut)',
    tell_host: 'Illusoq-mi suliliaq',
    per_night_short: 'DKK / unnuamut',
    transport: 'Umiarsuit',
    nights_label: 'DKK × unnuap',
    login_to_book: 'Booking-eruk loggi',
    secure_payment: 'Sikker payment Stripe',
    back_to_cabins: 'Illut siunnertat',
    cabin_not_found: 'Illu takunngissuq',
    up_to_guests: 'Inuit',
    host_provides_transport: 'Illusoq umiarsuit',
    select_dates_to_book: 'Ulloq takuuk booking',
    routes_found: 'rute',
    no_transport_found: 'Umiarsuit noanngissagut',
    try_another_search: 'Ataata ujarlerit',
    local_offers: 'Nunaqarfinni umiarsuarait inissaat',
    transport_offered: 'Umiarsuit pissarsiat',
    write_review: 'Naliliineq allaguk',
    send_review: 'Naliliineq nassiuguk',
    share_experience_transport: 'Umiarsuit pillugu naliliineq...',
    no_reviews_yet: 'Naliliinerit suli.',
    anonymous: 'Ateqanngitsoq',
    review_sent: 'Naliliineq nassiunneqarpoq',
    review_sent_desc: 'Qujanaq!',
    all_locations: 'Tamarmik sumiiffinni',
    newest_first: 'Nutaat siulliit',
    price_low_high: 'Akiliut: mikisoq-angisoq',
    price_high_low: 'Akiliut: angisoq-mikisoq',
    advanced: 'Siunnertat',
    min_price_label: 'Min akiliut (DKK/unnuamut)',
    max_price_label: 'Max akiliut (DKK/unnuamut)',
    min_guests_label: 'Min. inuit',
    check_in_after: 'Illu-eruk kingorna',
    amenities_label: 'Atorfinitsit',
    host_offers_transport: 'Illusoq umiarsuit',
    reset_filters: 'Suliaq aaqqissuussaaq',
    search_cabin_placeholder: 'Ujarlerit...',
    all_departures: 'Tamarmik inisserit',
    all_destinations: 'Tamarmik attut',
    earliest_date: 'Ullua siulleq',
    max_price_seat: 'Max akiliut/inissaq (DKK)',
    min_seats_label: 'Min. inissat',
    boat_type_label: 'Umiarsuit allannguut',
    all_types: 'Tamarmik allannguut',
    search_route_placeholder: 'Rute ujarlerit...',
    round_trip_label: 'inisseq-paluartup',
    see_and_book: 'Takuuk & Booking',
    by_provider: '-mit',
    map_cabins: 'Illut',
    map_departures: 'Inisserit',
    map_destinations: 'Attut',
    map_per_night: '/unnuamut',
    map_see_details: 'Takuuk →',
    map_departure_port: 'Inisseriffik',
    map_destination_label: 'Attut',
    map_routes_available: 'rutiit',
    map_avg_roundtrip: 'Gns. inisseq-paluartup',
    map_see_all_routes: 'Tamarmik rutiit takuuk →',
    getting_there: 'Tikittarneq',
    host_provided_transport: 'Illusoq umiarsuit',
    host_no_transport: 'Illusoq umiarsuit naamik pissarsiat.',
    offers_transport_from: 'umiarsuit pissarsiat',
    to_the_cabin: 'illumut',
    the_mainland: 'nunap',
    i_want: 'Nalinginnaasumik:',
    round_trip_both: 'Inisseq-paluartup',
    outbound_one_way: 'Inisseq aataatigut',
    return_one_way: 'Paluartup aataatigut',
    guest_singular: 'inuk',
    guest_plural: 'inuit',
    added_to_total: 'booking-imut ilanngunneqarpoq',
    return_included: 'Paluartup ilanngullugu',
    no_transport_listings: 'Umiarsuit suli takunngissuq.',
    other_transport_to: 'Allanik umiarsuiit',
    date_doesnt_fit: 'Ullua siunngitsoorpa?',
    request_transport_now: 'Umiarsuanik ujarlerit',
    request_transport_heading: 'Umiarsuit ujarlerit',
    request_transport_subtitle: 'Nunaqarfinni umiarsuarait svaaq-eruk.',
    request_placeholder: 'Inugujoq...',
    request_success: 'Inissaq takutut!',
    request_success_desc: 'Umiarsuarait-quat svaaq-eruk.',
    send_another: 'Nutaamik takuuk',
    pay_amount: 'Akiliut',
    cancel: 'Aaqqissuussaaq',
    seats_left: 'inissat',
    with_cabin: 'Kabinimik',
    without_cabin: 'Kabinimik naamik',
    no_confirmed_return_any: 'Paluartup suli takunngissuq.',
    no_return_other_providers: 'Suliartortitsisoq uma paluartup naamik pissarsiat.\n\nAllanik atugaat umiarsuiit',
    send_request_all_providers: 'Inissaq takuuk — tamarmik nunaqarfinni umiarsuarait takuuk',
    request_sent_to_all_providers: 'Inissaq tamarmik umiarsuarait-mut nassiunneqarpoq.',
    request_sent_to_all_desc: 'Inissaq tamarmik umiarsuarait-mut nassiunneqassaaq. Akiliinngillat.',
    back_to_transport: 'Umiarsuit siunnertat',
    transport_not_found: 'Umiarsuit takunngissuq',
    seats_plural: 'inissat',
    total_label: 'Katillugit',
    fully_booked: 'Tamaat bookingeqarpoq',
    footer_desc: 'Kalaallit Nunaanni umiarsuarait illullu nunaqarfinni.',
    footer_explore: 'Ujarlerit',
    footer_browse_cabins: 'Illut takuuk',
    footer_find_transport: 'Umiarsuit nassaaruk',
    footer_hosts: 'Illusorit',
    footer_list_cabin: 'Illuk takuuk',
    footer_offer_transport: 'Umiarsuit pissarsiat',
    footer_learn: 'Ilinniaruk',
    footer_trust_score: 'Tunngaviguk',
    footer_verified_safety: 'Inugujoq Taperneq',
    footer_community_guidelines: 'Inerniarner Ataasinnguuq',
    footer_legal: 'Suliaq',
    footer_privacy_policy: 'Privatlivspolitik',
    footer_terms: 'Ataasinnguuq Suliaq',
    footer_cookies: 'Cookies',
    footer_support: 'Ikioqataaseriaat',
    footer_privacy_center: 'Privatlivscenter',
    footer_contact_support: 'Ikioqataaseriaat nassiuguk',
    cant_find_cabin: 'Illuk takunngitsumit?',
    request_cabin_cta: 'Suliliaq ataasiguk, inuk suliartortitsioruk innilissinnagu illumut.',
    cant_find_transport: 'Umiarsuit rutiinnik takunngitsumit?',
    request_transport_cta: 'Umiarsuit ujarlerit tamarmik illut attut innilissinnagu.',
    show_all_cabins: 'Tamarmik illut takuuk',
    show_all_transport: 'Tamarmik rutiit takuuk',
    incident_title: 'Inerniarneq Rapporterneq',
    incident_subtitle: 'Kina inugujoq taperneq inerniarninni asigissarpoq. Ataasunnguinneri aput rapporterneq.',
    incident_urgent: 'Alluugujoq?',
    incident_emergency_text: 'Inugujoq alluugujorneq ineriallarnissua, silaannik ataasinnguut tullimat.',
    incident_contact: 'Qujanaq?',
    incident_form_title: 'Inerniarneq Rapporterneq',
    incident_form_subtitle: 'Inugujoq taperneq ajunnginneri',
    incident_email: 'Kina E-mail',
    incident_type: 'Inerniarneq Taqqaq',
    incident_description: 'Inugujoq',
    incident_booking: 'Booking ID (uugujoq)',
    incident_involved: 'Ataasinnguut (e-mails, komma-asigissarneq)',
    incident_submit: 'Rapporterneq Iluaasigneri',
    incident_success: 'Inerniarneq rapporterneq alluunnik. Team-ip ataasunnguinneri 24-imi naatsumenera asigissarpoq.',
    incident_error: 'Alluugujoq rapporterneq iluaasigineqq',
    incident_report_submitted: 'Rapporterneq iluaasigineqq',
    incident_submit_another: 'Inuugujoq Rapporterneq',
    incident_select_type: 'Taqqaq uugujoq',
    incident_type_safety: 'Inugujoq',
    incident_type_harassment: 'Ataasunnguinneri',
    incident_type_fraud: 'Taatsinngisoq',
    incident_type_damage: 'Pilersuaq Alluugujoq',
    incident_type_other: 'Inuugujoq',
    support_title: 'Ikioqataaseriaat',
    support_subtitle: 'Booking, umiarsuit, illullu pillugit ikiorsinnaavugut.',
    support_faq_title: 'Nalunaarsuiffigeqqinnissaminnik',
    support_subject_label: 'Emne',
    support_subject_placeholder: 'Nalunaarsuiffigeqqinnissaminnik takuuk...',
    support_custom_subject_label: 'Emne suliliaq',
    support_custom_subject_placeholder: 'Nalunaarsuiffigeqqinnissaminnik...',
    support_message_label: 'Oqaatigineq',
    support_message_placeholder: 'Nalunaarsuiffigeqqinnissaminnik...',
    support_booking_id_label: 'Booking ID',
    support_booking_id_optional: '(uugujoq)',
    support_booking_id_placeholder: 'Booking pillugu',
    support_attachments_label: 'Nalunaarsuiffigeqqinnissaminnik',
    support_attachments_optional: '(uugujoq)',
    support_uploading: 'Nassatassuseq...',
    support_attach_files: 'Nalunaarsuiffigeqqinnissaminnik takuuk',
    support_sending: 'Nassatassuseq...',
    support_send_btn: 'Nassatassuerit',
    support_faq_answer_heading: 'Nalunaarsuiffigeqqinnissaminnik',
    support_faq_didnt_help: 'Ikiorsinnaanngitsumik? Iluarsimassariaqarpoq.',
    support_received_title: 'Nassatassueqataanngitsumik',
    support_received_desc: 'Oqaatiginerit support@sila.gl-mut 24-imi nassatassuserpoq.',
    support_new_inquiry: 'Nutaamik nassatassuerit',
    support_upload_error: 'Nassatassuseq alluugujoq',
    support_fill_fields: 'Tamarmik nalunaarsuiffigeqqinnissaminnik',
    support_incident_title: 'Inerniarneq Rapporterneq',
    support_incident_desc: 'Inugujoq taperneq inerniarninni asigissarpoq. Ataasunnguinneri aput rapporterneq.',
    support_incident_btn: 'Inerniarneq rapporterneq',
    faq_q1: 'Booking aaqqissuussaasoq?',
    faq_q2: 'Angallattariaqarfiit allanngorsinnaapput?',
    faq_q3: 'Akiliissinissaminnik sumiiffinni?',
    faq_q4: 'Suliartortitsisoq kissaatissatut?',
    faq_q5: 'Aaqqissuussaatissaminnik sumiiffinni?',
    faq_q6: 'Inugujoq rapporterneq?',
    faq_q7: 'Nassatassuseq booking-erneqanngitsumik',
    faq_q8: 'Illu/umiarsuit sulisoq',
    faq_other: 'Arlaaq — suliliaq...',
    faq_a1: 'Dashboard-imi "Mine bookinger" booking aaqqissuussaasoq. "Annuller" klikkit. support@sila.gl nassatassuerit.',
    faq_a2: 'Ulluat allanngorsinnaanngitsumik. Booking aaqqissuiissaaruk nutaamiklu sulisoq. Suliartortitsisoq chat-imi oqaatsisiissitissavaa.',
    faq_a3: 'Visa, Mastercard, American Express Stripe-imi. Akiliissinissaminnik sikkerhedeqarpoq.',
    faq_a4: 'Dashboard-imi booking/ujarlerit nassaaruk. Chat suliartortitsisoqarpoq.',
    faq_a5: 'Aaqqissuussaatissaminnik suliartortitsisoq pillugit. support@sila.gl nassatassuerit.',
    faq_a6: 'Inerniarneq rapporterneq "Rapportér en hændelse" oqaatsisiissitissavaa. support@sila.gl nassatassuerit.',
    faq_a7: 'Spam nassaaruk. no-reply@sila.gl-mit nassatassuserpoq. 10-imi noanngissagut, booking ID-mit nassatassuerit.',
    faq_a8: 'Dashboard → "Nyt opslag". Illu/umiarsuit sulisoq. support@sila.gl nassatassuerit.',
    ask_provider_title: 'Suliartortitsisoq nalunaarsuiffigeqqinnissaminnik',
    ask_provider_placeholder: 'Qimmeq? Nassatassuseq? Neriniarlutit?',
    ask_provider_send: 'Nalunaarsuiffigeqqinnissaminnik nassatassuerit',
    ask_provider_sending: 'Nassatassuseq...',
    ask_provider_sent: 'Nassatassueqataanngitsumik!',
    ask_provider_sent_desc: 'Suliartortitsisoq nalunaarsuiffigeqqinnissaminnik.',
    ask_provider_login: 'Loggi nalunaarsuiffigeqqinnissaminnik',
    welcome_to_sila: 'Tikilluarit Silamut 👋',
    complete_profile_subtitle: 'Udfyld din profil — det tager under et minut',
    get_started: 'Kom i gang',
    onboarding_name_required: 'Angiv venligst dit fulde navn.',
    onboarding_city_required: 'Vælg venligst din by.',
    onboarding_role_required: 'Vælg venligst din rolle.',
  },
  };

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    // Load from localStorage or default to 'da'
    if (typeof window !== 'undefined') {
      return localStorage.getItem('sila_language') || 'da';
    }
    return 'da';
  });

  const changeLang = (newLang) => {
    setLang(newLang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('sila_language', newLang);
    }
  };

  const t = (key) => {
    return translations[lang]?.[key] || translations['da']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}